name: Pytest

on:
  pull_request:
    branches:
        - dev
        - main
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install Python
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: imc_cpu
          mamba-version: "*"
          use-mamba: true
          channels: conda-forge
          environment-file: env.yml
          auto-activate-base: false
      
      - name: Install iMolCRAFT
        shell: bash -el {0}
        run: pip install '.[test]'

      - name: Run tests
        shell: bash -el {0}
        run: |
          pytest tests/test_analyzer -m "not g16"
          pytest tests/test_calculator -m "not g16"
          pytest tests/test_crafter -m "not g16"
          pytest tests/test_io -m "not g16"
          pytest tests/test_trainer -m "not g16"
